### ISSUE TITLE
Throwing error with medium-size Whisper model on 4070 laptop (8GB VRAM)

### ISSUE THREAD

**Issue by rikuddo91** [petermg/Chatterbox-TTS-Extended#40]
`[DEBUG] Validating all candidates with Whisper for all chunks (sequentially)...
[DEBUG] Loading faster-whisper model: medium
Traceback (most recent call last):
  File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\gradio\queueing.py", line 626, in process_events
    response = await route_utils.call_process_api(
  File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\gradio\route_utils.py", line 350, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\gradio\blocks.py", line 2235, in process_api
    result = await self.call_function(
  File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\gradio\blocks.py", line 1746, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2476, in run_sync_in_worker_thread
    return await future
  File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\gradio\utils.py", line 917, in wrapper
    response = f(*args, **kwargs)
  File "E:\DeepFake\Chatterbox-TTS-Extended\Chatter.py", line 1724, in <lambda>
    generate_and_preview(*args)
  File "E:\DeepFake\Chatterbox-TTS-Extended\Chatter.py", line 848, in generate_and_preview
    output_paths = generate_batch_tts(*args)
  File "E:\DeepFake\Chatterbox-TTS-Extended\Chatter.py", line 964, in generate_batch_tts
    return process_text_for_tts(
  File "E:\DeepFake\Chatterbox-TTS-Extended\Chatter.py", line 1143, in process_text_for_tts
    whisper_model = load_whisper_backend(model_key, use_faster_whisper, DEVICE)
  File "E:\DeepFake\Chatterbox-TTS-Extended\Chatter.py", line 267, in load_whisper_backend
    return FasterWhisperModel(model_name, device=device, compute_type="float16" if device=="cuda" else "float32")
  File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\faster_whisper\transcribe.py", line 647, in __init__
    self.model = ctranslate2.models.Whisper(`

It happens right after all the chunks have been generated and whisper validaion start it works. It used to worked perfectly fine with medium-size and same settings before the current update. These are the settings I'm using (I've also tried disabling 'sentence batching' but same result),
<img width="2327" height="1160" alt="Image" src="https://github.com/user-attachments/assets/3b0bdfd1-dd4e-47ff-be39-2148258e24a7" />

CPU 7940HS - 4070 (Laptop) 8GB VRAM.
Win 11  - 32GB DDR5 RAM

**Comment by petermg** [comment]
I will test this and report back.

**Comment by petermg** [comment]
> `[DEBUG] Validating all candidates with Whisper for all chunks (sequentially)... [DEBUG] Loading faster-whisper model: medium Traceback (most recent call last): File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\gradio\queueing.py", line 626, in process_events response = await route_utils.call_process_api( File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\gradio\route_utils.py", line 350, in call_process_api output = await app.get_blocks().process_api( File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\gradio\blocks.py", line 2235, in process_api result = await self.call_function( File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\gradio\blocks.py", line 1746, in call_function prediction = await anyio.to_thread.run_sync( # type: ignore File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2476, in run_sync_in_worker_thread return await future File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run result = context.run(func, *args) File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\gradio\utils.py", line 917, in wrapper response = f(*args, **kwargs) File "E:\DeepFake\Chatterbox-TTS-Extended\Chatter.py", line 1724, in <lambda> generate_and_preview(*args) File "E:\DeepFake\Chatterbox-TTS-Extended\Chatter.py", line 848, in generate_and_preview output_paths = generate_batch_tts(*args) File "E:\DeepFake\Chatterbox-TTS-Extended\Chatter.py", line 964, in generate_batch_tts return process_text_for_tts( File "E:\DeepFake\Chatterbox-TTS-Extended\Chatter.py", line 1143, in process_text_for_tts whisper_model = load_whisper_backend(model_key, use_faster_whisper, DEVICE) File "E:\DeepFake\Chatterbox-TTS-Extended\Chatter.py", line 267, in load_whisper_backend return FasterWhisperModel(model_name, device=device, compute_type="float16" if device=="cuda" else "float32") File "E:\DeepFake\Chatterbox-TTS-Extended\venv\lib\site-packages\faster_whisper\transcribe.py", line 647, in __init__ self.model = ctranslate2.models.Whisper(`
> 
> It happens right after all the chunks have been generated and whisper validaion start it works. It used to worked perfectly fine with medium-size and same settings before the current update. These are the settings I'm using (I've also tried disabling 'sentence batching' but same result), <img alt="Image" width="2000" height="1160" src="https://private-user-images.githubusercontent.com/70138239/478680270-3b0bdfd1-dd4e-47ff-be39-2148258e24a7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUzODkyOTMsIm5iZiI6MTc1NTM4ODk5MywicGF0aCI6Ii83MDEzODIzOS80Nzg2ODAyNzAtM2IwYmRmZDEtZGQ0ZS00N2ZmLWJlMzktMjE0ODI1OGUyNGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODE3VDAwMDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiOTY3ZmViZDNiNTZmMGJlZjMwYzFjODMyOTZjNTlmYmYxMDgzZWM1ZTlhZmFmMDAyMTE5MGFiYmQwYWM0NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L59LcDvYjI-aPPhzjmZI8d2s9RDdp-J6kj5KkvMXx10">
> 
> CPU 7940HS - 4070 (Laptop) 8GB VRAM. Win 11 - 32GB DDR5 RAM

Ok do a git pull and see if the latest patch I did fixed it for you.

**Comment by petermg** [comment]
I would also like to add that doing the validation doesn't really seem to be a need anymore. I don't use it and my audio generations turn out fine. Originally I was experiencing hallucinations because I had the chunk size too large. Scaling that back fixed that issue so I no longer use the validation. I suggest trying it. Also I think you can just set "Number of candidates per chunk" to 1 since the pyrrnoise and auto-editor seem to eliminate all artifacts. This makes getting through the process much faster.

**Comment by rikuddo91** [comment]
> I would also like to add that doing the validation doesn't really seem to be a need anymore. I don't use it and my audio generations turn out fine. Originally I was experiencing hallucinations because I had the chunk size too large. Scaling that back fixed that issue so I no longer use the validation. I suggest trying it. Also I think you can just set "Number of candidates per chunk" to 1 since the pyrrnoise and auto-editor seem to eliminate all artifacts. This makes getting through the process much faster.

 The problem is resolved, I can use the Medium model again. Thank you for quick fix :)

As for other settings, here's my experience so far,

- **Parallel Workers** to 1 works fantastic for me, and speed is much better overall (~22 it/s)
- **Denoise with RNNoise (pyrnnoise)** AND **Post Process with Audio Editor** --- the audio is very choppy, it sounds like roughly stiched together audio clips which cuts at random intervals.
- Using only **Denoise with RNNoise** --- that choppy issue is no more.
- **Bypassing Whisper** - There's at least one instance of either hallucination or quiet-period (where nothing is being spoken).

The ideal setting I've found for me is, having Max Attempts Per Candidate to 2, which remove any remaining hallucination and silence issues, parallel worker to 1, Post-Process Audio-Editor unchecked. 

This is not a big problem but with recent change, the output file name (0.Preface.txt)  is like this
0_Prefaceaudio_2025-08-17_120151_814_gen1_seed3956352381

Whereas, before it used be like this
0_Preface_audio_2025-08-16_163807_055_gen1_seed659245278

It's missing the underscore after the file name '0.Preface'. As I said, it's no emergency but I would love if you could add it in any later push.

Thank you for your work though, really appreciate it.

**Comment by petermg** [comment]
> > I would also like to add that doing the validation doesn't really seem to be a need anymore. I don't use it and my audio generations turn out fine. Originally I was experiencing hallucinations because I had the chunk size too large. Scaling that back fixed that issue so I no longer use the validation. I suggest trying it. Also I think you can just set "Number of candidates per chunk" to 1 since the pyrrnoise and auto-editor seem to eliminate all artifacts. This makes getting through the process much faster.
> 
> The problem is resolved, I can use the Medium model again. Thank you for quick fix :)
> 
> As for other settings, here's my experience so far,
> 
> * **Parallel Workers** to 1 works fantastic for me, and speed is much better overall (~22 it/s)
> * **Denoise with RNNoise (pyrnnoise)** AND **Post Process with Audio Editor** --- the audio is very choppy, it sounds like roughly stiched together audio clips which cuts at random intervals.
> * Using only **Denoise with RNNoise** --- that choppy issue is no more.
> * **Bypassing Whisper** - There's at least one instance of either hallucination or quiet-period (where nothing is being spoken).
> 
> The ideal setting I've found for me is, having Max Attempts Per Candidate to 2, which remove any remaining hallucination and silence issues, parallel worker to 1, Post-Process Audio-Editor unchecked.
> 
> This is not a big problem but with recent change, the output file name (0.Preface.txt) is like this 0_Prefaceaudio_2025-08-17_120151_814_gen1_seed3956352381
> 
> Whereas, before it used be like this 0_Preface_audio_2025-08-16_163807_055_gen1_seed659245278
> 
> It's missing the underscore after the file name '0.Preface'. As I said, it's no emergency but I would love if you could add it in any later push.
> 
> Thank you for your work though, really appreciate it.

Ok a couple of suggestions. When it comes to hallucinations, try checking the following option: "Enable Sentence Batching (Max 300 chars)". Apparently if this isn't checked it can do weird things, I think.
UNcheck "Smart-append short sentences (if batching is off)".
Can you please find out for me which version of auto-editor is installed? Please do "pip list |findstr auto" and see what version of auto-editor it shows. I'm guessing you're using reference audio for your generations and maybe the sample you're using is too low in volume and so the default threshold set for auto-editor is cutting places it shouldn't because it falls below the volume cutting threshold.

**Comment by petermg** [comment]
> This is not a big problem but with recent change, the output file name (0.Preface.txt) is like this 0_Prefaceaudio_2025-08-17_120151_814_gen1_seed3956352381
> 
> Whereas, before it used be like this 0_Preface_audio_2025-08-16_163807_055_gen1_seed659245278
> 
> It's missing the underscore after the file name '0.Preface'. As I said, it's no emergency but I would love if you could add it in any later push.

Oh BTW, do "git pull" to get the latest Chatter.py. It should solve this problem. I was seeing this too but it should be working now, at least it is for me right now.

**Comment by rikuddo91** [comment]
> > This is not a big problem but with recent change, the output file name (0.Preface.txt) is like this 0_Prefaceaudio_2025-08-17_120151_814_gen1_seed3956352381
> > Whereas, before it used be like this 0_Preface_audio_2025-08-16_163807_055_gen1_seed659245278
> > It's missing the underscore after the file name '0.Preface'. As I said, it's no emergency but I would love if you could add it in any later push.
> 
> Oh BTW, do "git pull" to get the latest Chatter.py. It should solve this problem. I was seeing this too but it should be working now, at least it is for me right now.

auto-editor -  27.1.1

It still output as 0_Prefaceaudio_2025-08-18_122611_712_gen1_seed3268147409 (after git pull).

But most importantly, the audio cuts are gone! unchecking **Smart-append short sentences (if batching is off)** fixed the issue, and I did an output with Bypass Whisper, and just using Audio-Editor and Denoise with RNNoise, it worked fast due to whisper bypass and the output was surprisingly good with no hallucinations and silence part. I'll still do some more tried to confirm because moving on to large chapters (at ~20 it/s) they'll take hours to generate, so better be sure before committing to those :D

Thank you again for making this, the result is really satisfactory at the least and amazing at best.

I have one last feature request (for now), would it possible to somehow save/output 'Elapsed Time' or 'Time Took to Generate' for each file? 
It would be really helpful to keep an eye on which chapter/file took how much time, in case I want to generate another variation with different settings.

**Comment by petermg** [comment]
> It still output as 0_Prefaceaudio_2025-08-18_122611_712_gen1_seed3268147409 (after git pull).

my bad, you're right. When selecting "Generate separate audio files per text file", it was still having this issue. I just updated it and it should be solved now!

**Comment by petermg** [comment]
> But most importantly, the audio cuts are gone! unchecking **Smart-append short sentences (if batching is off)** fixed the issue, and I did an output with Bypass Whisper, and just using Audio-Editor and Denoise with RNNoise, it worked fast due to whisper bypass and the output was surprisingly good with no hallucinations and silence part.

Yeah I think sometimes there are issues with Smart-append but it seems to only sometimes show up so it's hard for me to track down. I generally don't use it because I use the batching features but I think I'll end up doing more digging when I have more time to see what's really going on. Yeah the addition of pyrnnoise denoising has made such a dramatic improvement that I no longer use whipsersync nor do I generate multiple candidates anymore. It's crazy fast now.

**Comment by petermg** [comment]
> I have one last feature request (for now), would it possible to somehow save/output 'Elapsed Time' or 'Time Took to Generate' for each file?
> It would be really helpful to keep an eye on which chapter/file took how much time, in case I want to generate another variation with different settings.

Probably. I'll look into this. I'm out all day today though so when I get some time, and remember, I'll look into this.
